CREATE TABLE IF NOT EXISTS `video` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uuid` LONGTEXT NOT NULL,
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `alterao_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `criado_por` VARCHAR(255) DEFAULT NULL,
  `alterado_por` VARCHAR(255) DEFAULT NULL,
  `data` DATE DEFAULT NULL,
  `url` LONGTEXT,
  `titulo` VARCHAR(255) DEFAULT NULL,
  `descricao` LONGTEXT NOT NULL,
  `imagem` VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
