-- Opcional: garante schema public
CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.usuario (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            TEXT NOT NULL UNIQUE,
    nome            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE,
    senha_hash      VARCHAR(255) NOT NULL,
    organizacao_uuid TEXT NULL,
    ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em       TIMESTAMP NOT NULL DEFAULT NOW(),
    alterado_em     TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Opcional: trigger para manter alterado_em atualizado em updates diretos no banco
/*CREATE OR REPLACE FUNCTION public.fn_set_alterado_em()
RETURNS TRIGGER AS $$
BEGIN
    NEW.alterado_em := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_alterado_em_usuario ON public.usuario;

CREATE TRIGGER trg_set_alterado_em_usuario
BEFORE UPDATE ON public.usuario
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_alterado_em();
*/