CREATE TABLE IF NOT EXISTS public.usuario_organizacao (
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id                  INTEGER NOT NULL,
    organizacao_id              INTEGER NOT NULL,
    tipo                        VARCHAR(20) NOT NULL DEFAULT 'COLABORADOR',
    criado_por_usuario_id       INTEGER NULL,
    ativo                       BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em                   TIMESTAMP NOT NULL DEFAULT NOW(),
    alterado_em                 TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_usuario_organizacao_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES public.usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_usuario_organizacao_organizacao
        FOREIGN KEY (organizacao_id)
        REFERENCES public.organizacao (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_usuario_organizacao_criado_por
        FOREIGN KEY (criado_por_usuario_id)
        REFERENCES public.usuario (id)
        ON DELETE SET NULL,

    CONSTRAINT ck_usuario_organizacao_tipo
        CHECK (tipo IN ('DONO', 'COLABORADOR')),

    CONSTRAINT uq_usuario_organizacao_usuario_org
        UNIQUE (usuario_id, organizacao_id)
);

-- Garante apenas um DONO por organizacao.
CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_organizacao_dono_por_org
    ON public.usuario_organizacao (organizacao_id)
    WHERE tipo = 'DONO';

CREATE INDEX IF NOT EXISTS idx_usuario_organizacao_usuario_id
    ON public.usuario_organizacao (usuario_id);

CREATE INDEX IF NOT EXISTS idx_usuario_organizacao_organizacao_id
    ON public.usuario_organizacao (organizacao_id);

/*
DROP TRIGGER IF EXISTS trg_set_alterado_em_usuario_organizacao ON public.usuario_organizacao;

CREATE TRIGGER trg_set_alterado_em_usuario_organizacao
BEFORE UPDATE ON public.usuario_organizacao
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_alterado_em();
*/
