-- Model: Video
-- Source: src/app/admin/models/video/video.entity.ts

CREATE TABLE IF NOT EXISTS public.video (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid          TEXT NOT NULL,
  criado_em     TIMESTAMP NOT NULL DEFAULT NOW(),
  alterao_em    TIMESTAMP NOT NULL DEFAULT NOW(),
  criado_por    VARCHAR(255),
  alterado_por  VARCHAR(255),
  data          DATE,
  url           TEXT,
  titulo        VARCHAR(255),
  descricao     TEXT NOT NULL,
  imagem        VARCHAR(200)
);

CREATE INDEX IF NOT EXISTS idx_video_uuid ON public.video (uuid);
