export const apiFields = {
    cargos: {id: 'id', displayName: 'descricao'},
    cnae: {id: 'id', displayName: 'descricao'},
    classificacoesTributarias: {id: 'id', displayName: 'descricao'},
    esferaAdmOrgaoPublico: {id: 'id', displayName: 'descricao'},
    fpas: {id: 'id', code: 'id', displayName: 'codigo'},
    indicativoCooperativa: {id: 'id', displayName: 'descricao'},
    instituicaoOrgaoPublico: {id: 'id', displayName: 'descricao'},
    municipios: {id: 'id', displayName: 'descricao'},
    naturezasJuridicas: {id: 'id', code: 'codigo', displayName: 'descricao'},
    porteEmpresa: {id: 'id', displayName: 'descricao'},
    recolhimentoSefip: {id: 'id', displayName: 'descricao'},
    simples: {id: 'id', displayName: 'descricao'},
    usuarios: {id: 'id', displayName: 'nome'},
}